# Generated by Django 3.2.7 on 2021-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rolemodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buildmodel',
            name='type',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='role',
            field=models.TextField(unique=True),
        ),
    ]
