# Generated by Django 3.2.7 on 2021-09-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210914_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporttypemodel',
            name='type',
            field=models.TextField(unique=True),
        ),
    ]
