# Generated by Django 3.2.7 on 2021-09-14 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20210914_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistorymodel',
            name='build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.buildmodel'),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderhistorymodel',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usertransportmodel'),
        ),
    ]
