# Generated by Django 3.2.7 on 2021-09-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210915_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemodel',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
    ]
