# Generated by Django 3.2.7 on 2021-09-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transporttypemodel_is_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='code',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ordermodel'),
        ),
    ]
