# Generated by Django 3.2.7 on 2021-09-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210915_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'ordering': ['-id']},
        ),
    ]
