# Generated by Django 3.2.7 on 2021-09-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_itemmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
