# Generated by Django 3.2.7 on 2021-09-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_orderhistorymodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistorymodel',
            options={'ordering': ['id', 'queue']},
        ),
        migrations.AddField(
            model_name='orderhistorymodel',
            name='queue',
            field=models.IntegerField(default=0),
        ),
    ]
